import "dotenv/config";

import { randomBytes } from "node:crypto";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";
import { bootstrapRuntimeRole } from "./database-role-bootstrap";
import { verifyDatabaseRoles } from "./verify-database-roles";
import { verifyMigrationJournal } from "./verify-migration-journal";

function generateSecurePassword(length = 32): string {
  return randomBytes(length)
    .toString("base64")
    .replace(/[^a-zA-Z0-9]/g, "")
    .slice(0, length);
}

function buildRuntimeUrl(directUrl: string, runtimePassword: string): string {
  const url = new URL(directUrl);
  url.username = "komanda_runtime";
  url.password = runtimePassword;
  return url.toString();
}

async function main() {
  console.log("\n🚀 Komanda — Inicializador Universal de Base de Datos\n");

  const directUrl = process.env.DATABASE_DIRECT_URL ?? process.env.DATABASE_URL;
  if (!directUrl) {
    console.error("❌ Error: Se requiere DATABASE_DIRECT_URL o DATABASE_URL en las variables de entorno.");
    process.exit(1);
  }

  const parsedDirect = new URL(directUrl);
  console.log(`📡 Conectando a PostgreSQL en: ${parsedDirect.hostname}:${parsedDirect.port || 5432}/${parsedDirect.pathname.replace(/^\//, "")}`);
  console.log(`👤 Usuario de conexión administrativa: ${decodeURIComponent(parsedDirect.username)}`);

  const sslOption = directUrl.includes("localhost") || directUrl.includes("127.0.0.1")
    ? undefined
    : { rejectUnauthorized: false };

  const pool = new Pool({
    connectionString: directUrl,
    max: 1,
    ssl: sslOption,
  });

  const client = await pool.connect();
  try {
    const versionRes = await client.query<{ version: string }>("select version()");
    console.log(`ℹ️  Versión del motor: ${versionRes.rows[0]?.version.split(" on ")[0]}`);

    // 1. Extensiones requeridas
    console.log("\n⚙️  1/4 Verificando extensiones nativas de PostgreSQL...");
    await client.query('create extension if not exists "pg_trgm";');
    console.log("   ✓ Extensión pg_trgm habilitada (para búsqueda rápida trigram).");

    // 2. Provisionar roles de acceso (komanda_runtime y komanda_analytics)
    console.log("\n🔐 2/4 Provisionando roles con menor privilegio (Least Privilege)...");
    let runtimePassword =
      process.env.DATABASE_RUNTIME_PASSWORD ??
      process.env.KOMANDA_BOOTSTRAP_RUNTIME_PASSWORD;

    let autoGeneratedPassword = false;
    if (!runtimePassword || runtimePassword.length < 32) {
      runtimePassword = generateSecurePassword(32);
      autoGeneratedPassword = true;
    }

    await bootstrapRuntimeRole({
      connectionString: directUrl,
      runtimePassword,
    });
    console.log("   ✓ Rol komanda_runtime configurado (NOBYPASSRLS, sujeto a FORCE RLS).");
    console.log("   ✓ Rol komanda_analytics configurado (restringido a vistas sanitizadas).");

    // 3. Aplicar todas las migraciones (tablas, RLS, triggers y vistas)
    console.log("\n📦 3/4 Aplicando migraciones de Drizzle...");
    await migrate(drizzle(client), { migrationsFolder: "./drizzle" });
    const journalCheck = await verifyMigrationJournal({ connectionString: directUrl });
    console.log(`   ✓ ${journalCheck.sourceCount} migraciones aplicadas e indexadas en __drizzle_migrations.`);

    // 4. Auditar las 61 tablas y verificar aislamiento multi-tenant
    console.log("\n🛡️  4/4 Auditando FORCE ROW LEVEL SECURITY en todas las tablas...");
    const runtimeUrl = process.env.DATABASE_URL && process.env.DATABASE_URL.includes("komanda_runtime")
      ? process.env.DATABASE_URL
      : buildRuntimeUrl(directUrl, runtimePassword);

    await verifyDatabaseRoles({
      runtimeUrl,
      migrationUrl: directUrl,
    });
    console.log("   ✓ Las 61 tablas protegidas tienen rowsecurity=true y forcerowsecurity=true.");
    console.log("   ✓ Verificación de aislamiento multi-tenant exitosa.");

    console.log("\n========================================================");
    console.log("🎉 ¡BASE DE DATOS INICIALIZADA Y LISTA PARA USAR!");
    console.log("========================================================\n");
    console.log("Para tu archivo .env, configurá las siguientes cadenas:\n");
    console.log(`DATABASE_DIRECT_URL="${directUrl}"`);
    console.log(`DATABASE_URL="${runtimeUrl}"`);
    if (autoGeneratedPassword) {
      console.log(`DATABASE_RUNTIME_PASSWORD="${runtimePassword}"`);
    }
    console.log("\n========================================================\n");
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((error: unknown) => {
  console.error("\n❌ Error durante la inicialización de base de datos:");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
